build:
  nodes:
    analysis:
      dependencies:
        before:
          - composer require --dev johnpbloch/wordpress

filter:
  excluded_paths:
    - 'tests/*'
    - "*/ace-min-noconflict/*"
    - 'vendor/*'
    - '*.min.js'
  dependency_paths:
    - wordpress/
    - vendor/